name: word_collection_utils
description: A Dart library designed to simplify the processing of CSV files and provide
  utility functions for word collection management.
version: 0.1.2
repository: https://github.com/thecasualdev17/word_collection_utils

environment:
  sdk: ^3.7.2

dependencies:
  mocktail: ^1.0.4
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.0.4
  lints: ^5.0.0
  test: ^1.24.0
  
