name: word_collection_utils
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/thecasualdev17/word_collection_utils

environment:
  sdk: ^3.7.2

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
